# Generated by Django 3.0.5 on 2020-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_handling', '0001_initial'),
        ('collection_handling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(related_name='collections', to='image_handling.Image'),
        ),
    ]
