# Generated by Django 3.0.5 on 2020-05-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_handling', '0001_initial'),
        ('myauth', '0001_initial'),
        ('board_handling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='images',
            field=models.ManyToManyField(related_name='boards', to='image_handling.Image'),
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='myauth.Consumer'),
        ),
    ]
